package com.apulse.middleware.api;

public class DashboardHtml {
    private DashboardHtml() {}

    public static String getHtml() {
        return "<!DOCTYPE html>\n"
            + "<html lang=\"ko\">\n"
            + "<head>\n"
            + "<meta charset=\"UTF-8\">\n"
            + "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
            + "<title>RFID Middleware Dashboard</title>\n"
            + "<style>\n"
            + getStyles()
            + "</style>\n"
            + "</head>\n"
            + "<body>\n"
            + getBodyHtml()
            + "<script>\n"
            + getScript()
            + "</script>\n"
            + "</body>\n"
            + "</html>";
    }

    private static String getStyles() {
        return "*{margin:0;padding:0;box-sizing:border-box}\n"
            + "body{font-family:'Segoe UI',sans-serif;background:#f0f2f5;color:#333}\n"
            + "header{background:#1a73e8;color:#fff;padding:12px 24px;display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:8px}\n"
            + "header h1{font-size:18px;font-weight:600}\n"
            + ".ctrl-btns{display:flex;gap:6px;flex-wrap:wrap}\n"
            + ".ctrl-btns button{padding:6px 14px;border:1px solid rgba(255,255,255,.4);border-radius:4px;background:transparent;color:#fff;cursor:pointer;font-size:13px;transition:background .2s}\n"
            + ".ctrl-btns button:hover{background:rgba(255,255,255,.2)}\n"
            + ".tabs{display:flex;background:#fff;border-bottom:2px solid #e0e0e0}\n"
            + ".tabs button{padding:10px 24px;border:none;background:none;cursor:pointer;font-size:14px;color:#666;border-bottom:2px solid transparent;margin-bottom:-2px;transition:all .2s}\n"
            + ".tabs button.active{color:#1a73e8;border-bottom-color:#1a73e8;font-weight:600}\n"
            + ".tabs button:hover{color:#1a73e8}\n"
            + ".tab-content{display:none;padding:16px 24px}\n"
            + ".tab-content.active{display:block}\n"
            + "table{width:100%;border-collapse:collapse;background:#fff;border-radius:6px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,.1)}\n"
            + "th{background:#f8f9fa;padding:10px 12px;text-align:left;font-size:13px;color:#555;border-bottom:2px solid #e0e0e0;white-space:nowrap}\n"
            + "td{padding:8px 12px;border-bottom:1px solid #f0f0f0;font-size:13px}\n"
            + "tr:hover{background:#f5f8ff}\n"
            + "tr.clickable{cursor:pointer}\n"
            + ".toolbar{display:flex;gap:8px;margin-bottom:12px;align-items:center;flex-wrap:wrap}\n"
            + ".toolbar input,.toolbar select{padding:6px 10px;border:1px solid #ccc;border-radius:4px;font-size:13px}\n"
            + ".toolbar button,.form-row button{padding:6px 16px;border:none;border-radius:4px;background:#1a73e8;color:#fff;cursor:pointer;font-size:13px;transition:background .2s}\n"
            + ".toolbar button:hover,.form-row button:hover{background:#1557b0}\n"
            + ".btn-danger{background:#dc3545!important}\n"
            + ".btn-danger:hover{background:#b02a37!important}\n"
            + ".form-section{background:#fff;border-radius:6px;padding:16px;margin-bottom:16px;box-shadow:0 1px 3px rgba(0,0,0,.1)}\n"
            + ".form-section h3{font-size:14px;margin-bottom:10px;color:#333}\n"
            + ".form-row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}\n"
            + ".form-row input{padding:6px 10px;border:1px solid #ccc;border-radius:4px;font-size:13px}\n"
            + ".form-row label{font-size:13px;color:#555;min-width:60px}\n"
            + ".modal-overlay{display:none;position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,.5);z-index:1000;justify-content:center;align-items:center}\n"
            + ".modal-overlay.show{display:flex}\n"
            + ".modal{background:#fff;border-radius:8px;padding:24px;min-width:400px;max-width:500px;box-shadow:0 4px 20px rgba(0,0,0,.3)}\n"
            + ".modal h3{margin-bottom:16px;font-size:16px}\n"
            + ".modal .field{margin-bottom:12px}\n"
            + ".modal .field label{display:block;font-size:13px;color:#555;margin-bottom:4px}\n"
            + ".modal .field input,.modal .field select{width:100%;padding:8px;border:1px solid #ccc;border-radius:4px;font-size:13px}\n"
            + ".modal .modal-btns{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}\n"
            + ".modal .modal-btns button{padding:8px 20px;border:none;border-radius:4px;cursor:pointer;font-size:13px}\n"
            + ".modal .modal-btns .btn-save{background:#1a73e8;color:#fff}\n"
            + ".modal .modal-btns .btn-cancel{background:#e0e0e0;color:#333}\n"
            + ".status-badge{display:inline-block;padding:2px 8px;border-radius:10px;font-size:11px;font-weight:600}\n"
            + ".status-CONNECTED{background:#d4edda;color:#155724}\n"
            + ".status-DISCONNECTED{background:#f8d7da;color:#721c24}\n"
            + ".status-INVENTORYING{background:#cce5ff;color:#004085}\n"
            + ".status-CONNECTING{background:#fff3cd;color:#856404}\n"
            + ".perm-valid{background:#d4edda;color:#155724}\n"
            + ".perm-expired{background:#f8d7da;color:#721c24}\n"
            + ".toast{position:fixed;bottom:20px;right:20px;padding:12px 20px;border-radius:6px;color:#fff;font-size:13px;z-index:2000;opacity:0;transition:opacity .3s}\n"
            + ".toast.show{opacity:1}\n"
            + ".toast.success{background:#28a745}\n"
            + ".toast.error{background:#dc3545}\n"
            + ".empty-msg{text-align:center;padding:40px;color:#999;font-size:14px}\n"
            + "tr.tag-alert{background:#fff0f0}\n"
            + "tr.tag-permitted{background:#f0fff0}\n"
            + ".auto-badge{display:inline-block;padding:2px 6px;border-radius:8px;font-size:10px;margin-left:8px}\n"
            + ".auto-on{background:#d4edda;color:#155724}\n"
            + ".auto-off{background:#f8d7da;color:#721c24}\n";
    }

    private static String getBodyHtml() {
        return "<header>\n"
            + "  <h1>RFID Middleware Dashboard</h1>\n"
            + "  <div class=\"ctrl-btns\">\n"
            + "    <button onclick=\"ctrlAction('connect-all')\">전체 연결</button>\n"
            + "    <button onclick=\"ctrlAction('disconnect-all')\">전체 해제</button>\n"
            + "    <button onclick=\"ctrlAction('start-inventory')\">인벤토리 시작</button>\n"
            + "    <button onclick=\"ctrlAction('stop-inventory')\">인벤토리 중지</button>\n"
            + "  </div>\n"
            + "</header>\n"
            + "<div class=\"tabs\">\n"
            + "  <button class=\"active\" onclick=\"switchTab('readers')\">리더기</button>\n"
            + "  <button onclick=\"switchTab('tags')\">태그데이터</button>\n"
            + "  <button onclick=\"switchTab('assets')\">자산 목록</button>\n"
            + "  <button onclick=\"switchTab('permissions')\">반출허용</button>\n"
            + "  <button onclick=\"switchTab('alerts')\">반출알림</button>\n"
            + "</div>\n"
            + "\n"
            // Readers tab
            + "<div id=\"tab-readers\" class=\"tab-content active\">\n"
            + "  <div class=\"toolbar\"><button onclick=\"loadReaders()\">새로고침</button></div>\n"
            + "  <div id=\"readers-table\"></div>\n"
            + "</div>\n"
            + "\n"
            // Tags tab
            + "<div id=\"tab-tags\" class=\"tab-content\">\n"
            + "  <div class=\"toolbar\">\n"
            + "    <button onclick=\"clearTags()\">태그 초기화</button>\n"
            + "    <span id=\"tag-status\" style=\"font-size:13px;color:#666\"></span>\n"
            + "  </div>\n"
            + "  <div id=\"tags-table\"></div>\n"
            + "</div>\n"
            + "\n"
            // Assets tab
            + "<div id=\"tab-assets\" class=\"tab-content\">\n"
            + "  <div class=\"toolbar\"><button onclick=\"loadAssets()\">새로고침</button></div>\n"
            + "  <div id=\"assets-table\"></div>\n"
            + "</div>\n"
            + "\n"
            // Permissions tab
            + "<div id=\"tab-permissions\" class=\"tab-content\">\n"
            + "  <div class=\"form-section\">\n"
            + "    <h3>반출허용 추가</h3>\n"
            + "    <div class=\"form-row\">\n"
            + "      <label>EPC</label><input id=\"perm-epc\" placeholder=\"EPC\" style=\"width:200px\">\n"
            + "      <label>시작</label><input id=\"perm-start\" type=\"datetime-local\">\n"
            + "      <label>종료</label><input id=\"perm-end\" type=\"datetime-local\">\n"
            + "      <label>사유</label><input id=\"perm-reason\" placeholder=\"반출 사유\" style=\"width:160px\">\n"
            + "      <button onclick=\"addPermission()\">추가</button>\n"
            + "    </div>\n"
            + "  </div>\n"
            + "  <div class=\"toolbar\"><button onclick=\"loadPermissions()\">새로고침</button></div>\n"
            + "  <div id=\"permissions-table\"></div>\n"
            + "</div>\n"
            + "\n"
            // Alerts tab
            + "<div id=\"tab-alerts\" class=\"tab-content\">\n"
            + "  <div class=\"toolbar\">\n"
            + "    <label>시작:</label><input id=\"alert-from\" type=\"datetime-local\">\n"
            + "    <label>종료:</label><input id=\"alert-to\" type=\"datetime-local\">\n"
            + "    <button onclick=\"loadAlerts()\">조회</button>\n"
            + "  </div>\n"
            + "  <div id=\"alerts-table\"></div>\n"
            + "</div>\n"
            + "\n"
            // Reader edit modal
            + "<div id=\"reader-modal\" class=\"modal-overlay\">\n"
            + "  <div class=\"modal\">\n"
            + "    <h3>리더기 설정 수정</h3>\n"
            + "    <div class=\"field\"><label>리더기명</label><input id=\"rm-name\" readonly></div>\n"
            + "    <div class=\"field\"><label>IP</label><input id=\"rm-ip\"></div>\n"
            + "    <div class=\"field\"><label>포트</label><input id=\"rm-port\" type=\"number\"></div>\n"
            + "    <div class=\"field\"><label>부저</label><select id=\"rm-buzzer\"><option value=\"true\">적용</option><option value=\"false\">해제</option></select></div>\n"
            + "    <div class=\"field\"><label>경광등</label><select id=\"rm-light\"><option value=\"true\">적용</option><option value=\"false\">해제</option></select></div>\n"
            + "    <div class=\"field\"><label>안테나 출력 (1/2/3/4)</label>\n"
            + "      <div style=\"display:flex;gap:6px\">\n"
            + "        <input id=\"rm-pw1\" type=\"number\" style=\"width:60px\">\n"
            + "        <input id=\"rm-pw2\" type=\"number\" style=\"width:60px\">\n"
            + "        <input id=\"rm-pw3\" type=\"number\" style=\"width:60px\">\n"
            + "        <input id=\"rm-pw4\" type=\"number\" style=\"width:60px\">\n"
            + "      </div>\n"
            + "    </div>\n"
            + "    <div class=\"field\"><label>드웰시간 (ms)</label><input id=\"rm-dwell\" type=\"number\"></div>\n"
            + "    <div class=\"modal-btns\">\n"
            + "      <button class=\"btn-cancel\" onclick=\"closeModal()\">취소</button>\n"
            + "      <button class=\"btn-save\" onclick=\"saveReader()\">저장</button>\n"
            + "    </div>\n"
            + "  </div>\n"
            + "</div>\n"
            + "\n"
            + "<div id=\"toast\" class=\"toast\"></div>\n";
    }

    private static String getScript() {
        return "function switchTab(name){\n"
            + "  document.querySelectorAll('.tab-content').forEach(function(el){el.classList.remove('active')});\n"
            + "  document.querySelectorAll('.tabs button').forEach(function(el){el.classList.remove('active')});\n"
            + "  document.getElementById('tab-'+name).classList.add('active');\n"
            + "  var btns=document.querySelectorAll('.tabs button');\n"
            + "  var tabs=['readers','tags','assets','permissions','alerts'];\n"
            + "  for(var i=0;i<tabs.length;i++){if(tabs[i]===name)btns[i].classList.add('active');}\n"
            + "  if(name==='readers')loadReaders();\n"
            + "  else if(name==='tags'){loadTags();startTagPoll();}\n"
            + "  else if(name==='assets')loadAssets();\n"
            + "  else if(name==='permissions')loadPermissions();\n"
            + "  if(name!=='tags')stopTagPoll();\n"
            + "}\n"
            + "\n"
            + "function showToast(msg,type){\n"
            + "  var t=document.getElementById('toast');\n"
            + "  t.textContent=msg;t.className='toast '+type+' show';\n"
            + "  setTimeout(function(){t.classList.remove('show')},3000);\n"
            + "}\n"
            + "\n"
            + "function api(method,url,body){\n"
            + "  var opts={method:method,headers:{'Content-Type':'application/json'}};\n"
            + "  if(body)opts.body=JSON.stringify(body);\n"
            + "  return fetch(url,opts).then(function(r){return r.json()});\n"
            + "}\n"
            + "\n"
            // Control actions
            + "function ctrlAction(action){\n"
            + "  api('POST','/api/control/'+action).then(function(r){\n"
            + "    if(r.status==='ok')showToast(r.data.message,'success');\n"
            + "    else showToast(r.message,'error');\n"
            + "    setTimeout(loadReaders,1000);\n"
            + "  }).catch(function(e){showToast('\uc624\ub958: '+e.message,'error')});\n"
            + "}\n"
            + "\n"
            // Readers
            + "function loadReaders(){\n"
            + "  api('GET','/api/readers').then(function(r){\n"
            + "    if(r.status!=='ok'){document.getElementById('readers-table').innerHTML='<div class=\"empty-msg\">'+r.message+'</div>';return;}\n"
            + "    var d=r.data;\n"
            + "    if(!d.length){document.getElementById('readers-table').innerHTML='<div class=\"empty-msg\">\ub9ac\ub354\uae30 \uc5c6\uc74c</div>';return;}\n"
            + "    var h='<table><tr><th>\uc774\ub984</th><th>IP</th><th>\ud3ec\ud2b8</th><th>\ubd80\uc800</th><th>\uacbd\uad11\ub4f1</th><th>\uc548\ud14c\ub098 \ucd9c\ub825</th><th>\ub4dc\uc6f0(ms)</th><th>\uc0c1\ud0dc</th></tr>';\n"
            + "    for(var i=0;i<d.length;i++){\n"
            + "      var x=d[i];\n"
            + "      h+='<tr class=\"clickable\" onclick=\"openReaderModal('+i+')\">';\n"
            + "      h+='<td>'+esc(x.name)+'</td>';\n"
            + "      h+='<td>'+esc(x.ip)+'</td>';\n"
            + "      h+='<td>'+x.port+'</td>';\n"
            + "      h+='<td>'+(x.buzzer?'\uc801\uc6a9':'\ud574\uc81c')+'</td>';\n"
            + "      h+='<td>'+(x.warningLight?'\uc801\uc6a9':'\ud574\uc81c')+'</td>';\n"
            + "      h+='<td>'+x.antennaPowers.join(' / ')+'</td>';\n"
            + "      h+='<td>'+x.dwellTime+'</td>';\n"
            + "      h+='<td><span class=\"status-badge status-'+x.status+'\">'+x.status+'</span></td>';\n"
            + "      h+='</tr>';\n"
            + "    }\n"
            + "    h+='</table>';\n"
            + "    document.getElementById('readers-table').innerHTML=h;\n"
            + "    window._readers=d;\n"
            + "  }).catch(function(e){document.getElementById('readers-table').innerHTML='<div class=\"empty-msg\">\uc624\ub958: '+e.message+'</div>';});\n"
            + "}\n"
            + "\n"
            // Reader modal
            + "function openReaderModal(idx){\n"
            + "  var x=window._readers[idx];\n"
            + "  document.getElementById('rm-name').value=x.name;\n"
            + "  document.getElementById('rm-ip').value=x.ip;\n"
            + "  document.getElementById('rm-port').value=x.port;\n"
            + "  document.getElementById('rm-buzzer').value=String(x.buzzer);\n"
            + "  document.getElementById('rm-light').value=String(x.warningLight);\n"
            + "  document.getElementById('rm-pw1').value=x.antennaPowers[0];\n"
            + "  document.getElementById('rm-pw2').value=x.antennaPowers[1];\n"
            + "  document.getElementById('rm-pw3').value=x.antennaPowers[2];\n"
            + "  document.getElementById('rm-pw4').value=x.antennaPowers[3];\n"
            + "  document.getElementById('rm-dwell').value=x.dwellTime;\n"
            + "  document.getElementById('reader-modal').classList.add('show');\n"
            + "}\n"
            + "\n"
            + "function closeModal(){document.getElementById('reader-modal').classList.remove('show');}\n"
            + "\n"
            + "function saveReader(){\n"
            + "  var name=document.getElementById('rm-name').value;\n"
            + "  var body={\n"
            + "    ip:document.getElementById('rm-ip').value,\n"
            + "    port:parseInt(document.getElementById('rm-port').value),\n"
            + "    buzzer:document.getElementById('rm-buzzer').value==='true',\n"
            + "    warningLight:document.getElementById('rm-light').value==='true',\n"
            + "    antennaPower1:parseInt(document.getElementById('rm-pw1').value),\n"
            + "    antennaPower2:parseInt(document.getElementById('rm-pw2').value),\n"
            + "    antennaPower3:parseInt(document.getElementById('rm-pw3').value),\n"
            + "    antennaPower4:parseInt(document.getElementById('rm-pw4').value),\n"
            + "    dwellTime:parseInt(document.getElementById('rm-dwell').value)\n"
            + "  };\n"
            + "  api('PUT','/api/readers/'+encodeURIComponent(name),body).then(function(r){\n"
            + "    if(r.status==='ok'){showToast('\uc800\uc7a5 \uc644\ub8cc','success');closeModal();loadReaders();}\n"
            + "    else showToast(r.message,'error');\n"
            + "  }).catch(function(e){showToast('\uc624\ub958: '+e.message,'error')});\n"
            + "}\n"
            + "\n"
            // Assets
            + "function loadAssets(){\n"
            + "  api('GET','/api/assets').then(function(r){\n"
            + "    if(r.status!=='ok'){document.getElementById('assets-table').innerHTML='<div class=\"empty-msg\">'+r.message+'</div>';return;}\n"
            + "    var d=r.data;\n"
            + "    if(!d.length){document.getElementById('assets-table').innerHTML='<div class=\"empty-msg\">\ub370\uc774\ud130 \uc5c6\uc74c</div>';return;}\n"
            + "    var h='<table><tr><th>\uc790\uc0b0\ubc88\ud638</th><th>EPC</th><th>\uc790\uc0b0\uba85</th><th>\ubd80\uc11c</th><th>\ubcf4\uc720\uc5ec\ubd80</th><th>\ub4f1\ub85d\uc77c</th></tr>';\n"
            + "    for(var i=0;i<d.length;i++){\n"
            + "      h+='<tr><td>'+esc(d[i].assetNumber)+'</td><td>'+esc(d[i].epc)+'</td><td>'+esc(d[i].assetName)+'</td><td>'+esc(d[i].department)+'</td><td>'+(d[i].possession?'\\ubcf4\\uc720':'\\ubbf8\\ubcf4\\uc720')+'</td><td>'+esc(d[i].createdAt)+'</td></tr>';\n"
            + "    }\n"
            + "    h+='</table>';\n"
            + "    document.getElementById('assets-table').innerHTML=h;\n"
            + "  }).catch(function(e){document.getElementById('assets-table').innerHTML='<div class=\"empty-msg\">\uc624\ub958: '+e.message+'</div>';});\n"
            + "}\n"
            + "\n"
            // Permissions
            + "function loadPermissions(){\n"
            + "  api('GET','/api/export-permissions').then(function(r){\n"
            + "    if(r.status!=='ok'){document.getElementById('permissions-table').innerHTML='<div class=\"empty-msg\">'+r.message+'</div>';return;}\n"
            + "    var d=r.data;\n"
            + "    if(!d.length){document.getElementById('permissions-table').innerHTML='<div class=\"empty-msg\">\ub370\uc774\ud130 \uc5c6\uc74c</div>';return;}\n"
            + "    var h='<table><tr><th>EPC</th><th>\uc790\uc0b0\ubc88\ud638</th><th>\uc790\uc0b0\uba85</th><th>\ud5c8\uc6a9\uc2dc\uc791</th><th>\ud5c8\uc6a9\uc885\ub8cc</th><th>\uc0ac\uc720</th><th>\uc0c1\ud0dc</th><th></th></tr>';\n"
            + "    for(var i=0;i<d.length;i++){\n"
            + "      var x=d[i];\n"
            + "      var cls=x.status==='\uc720\ud6a8'?'perm-valid':'perm-expired';\n"
            + "      h+='<tr><td>'+esc(x.epc)+'</td><td>'+esc(x.assetNumber)+'</td><td>'+esc(x.assetName)+'</td><td>'+esc(x.permitStart)+'</td><td>'+esc(x.permitEnd)+'</td><td>'+esc(x.reason)+'</td>';\n"
            + "      h+='<td><span class=\"status-badge '+cls+'\">'+esc(x.status)+'</span></td>';\n"
            + "      h+='<td><button class=\"btn-danger\" style=\"padding:3px 10px;font-size:12px\" onclick=\"deletePerm('+x.id+',\\''+esc(x.epc)+'\\')\">\uc0ad\uc81c</button></td></tr>';\n"
            + "    }\n"
            + "    h+='</table>';\n"
            + "    document.getElementById('permissions-table').innerHTML=h;\n"
            + "    window._perms=d;\n"
            + "  }).catch(function(e){document.getElementById('permissions-table').innerHTML='<div class=\"empty-msg\">\uc624\ub958: '+e.message+'</div>';});\n"
            + "}\n"
            + "\n"
            + "function addPermission(){\n"
            + "  var epc=document.getElementById('perm-epc').value.trim();\n"
            + "  var start=document.getElementById('perm-start').value;\n"
            + "  var end=document.getElementById('perm-end').value;\n"
            + "  var reason=document.getElementById('perm-reason').value.trim();\n"
            + "  if(!epc||!start||!end){showToast('EPC, \uc2dc\uc791, \uc885\ub8cc\ub294 \ud544\uc218\uc785\ub2c8\ub2e4','error');return;}\n"
            + "  var body={epc:epc,permitStart:start.replace('T',' ')+':00',permitEnd:end.replace('T',' ')+':00',reason:reason};\n"
            + "  api('POST','/api/export-permissions',body).then(function(r){\n"
            + "    if(r.status==='ok'){showToast('\ubc18\ucd9c\ud5c8\uc6a9 \ucd94\uac00 \uc644\ub8cc','success');loadPermissions();\n"
            + "      document.getElementById('perm-epc').value='';document.getElementById('perm-start').value='';document.getElementById('perm-end').value='';document.getElementById('perm-reason').value='';}\n"
            + "    else showToast(r.message,'error');\n"
            + "  }).catch(function(e){showToast('\uc624\ub958: '+e.message,'error')});\n"
            + "}\n"
            + "\n"
            + "function deletePerm(id,epc){\n"
            + "  if(!confirm('EPC: '+epc+'\\n\uc0ad\uc81c\ud558\uc2dc\uaca0\uc2b5\ub2c8\uae4c?'))return;\n"
            + "  api('DELETE','/api/export-permissions/'+id).then(function(r){\n"
            + "    if(r.status==='ok'){showToast('\uc0ad\uc81c \uc644\ub8cc','success');loadPermissions();}\n"
            + "    else showToast(r.message,'error');\n"
            + "  }).catch(function(e){showToast('\uc624\ub958: '+e.message,'error')});\n"
            + "}\n"
            + "\n"
            // Alerts
            + "function loadAlerts(){\n"
            + "  var from=document.getElementById('alert-from').value;\n"
            + "  var to=document.getElementById('alert-to').value;\n"
            + "  if(!from||!to){showToast('\uc2dc\uc791/\uc885\ub8cc \uae30\uac04\uc744 \uc785\ub825\ud558\uc138\uc694','error');return;}\n"
            + "  var qs='from='+encodeURIComponent(from.replace('T',' ')+':00')+'&to='+encodeURIComponent(to.replace('T',' ')+':00');\n"
            + "  api('GET','/api/export-alerts?'+qs).then(function(r){\n"
            + "    if(r.status!=='ok'){document.getElementById('alerts-table').innerHTML='<div class=\"empty-msg\">'+r.message+'</div>';return;}\n"
            + "    var d=r.data;\n"
            + "    if(!d.length){document.getElementById('alerts-table').innerHTML='<div class=\"empty-msg\">\ub370\uc774\ud130 \uc5c6\uc74c</div>';return;}\n"
            + "    var h='<table><tr><th>\uc54c\ub9bc\uc2dc\uac04</th><th>\ub9ac\ub354\uae30</th><th>EPC</th><th>\uc790\uc0b0\ubc88\ud638</th><th>\uc790\uc0b0\uba85</th><th>RSSI</th></tr>';\n"
            + "    for(var i=0;i<d.length;i++){\n"
            + "      h+='<tr><td>'+esc(d[i].alertTime)+'</td><td>'+esc(d[i].readerName)+'</td><td>'+esc(d[i].epc)+'</td><td>'+esc(d[i].assetNumber)+'</td><td>'+esc(d[i].assetName)+'</td><td>'+d[i].rssi+'</td></tr>';\n"
            + "    }\n"
            + "    h+='</table>';\n"
            + "    document.getElementById('alerts-table').innerHTML=h;\n"
            + "  }).catch(function(e){document.getElementById('alerts-table').innerHTML='<div class=\"empty-msg\">\uc624\ub958: '+e.message+'</div>';});\n"
            + "}\n"
            + "\n"
            // Tags
            + "var _tagPollTimer=null;\n"
            + "var _lastTagSeq=0;\n"
            + "\n"
            + "function loadTags(){\n"
            + "  api('GET','/api/tags/recent').then(function(r){\n"
            + "    if(r.status!=='ok'){document.getElementById('tags-table').innerHTML='<div class=\"empty-msg\">'+r.message+'</div>';return;}\n"
            + "    var d=r.data;\n"
            + "    _lastTagSeq=d.seq;\n"
            + "    document.getElementById('tag-status').innerHTML='\ucd1d '+d.tags.length+'\uac74';\n"
            + "    if(!d.tags.length){document.getElementById('tags-table').innerHTML='<div class=\"empty-msg\">\ud0dc\uadf8 \ub370\uc774\ud130 \uc5c6\uc74c</div>';return;}\n"
            + "    var h='<table><tr><th>\uc2dc\uac04</th><th>\ub9ac\ub354\uae30</th><th>EPC</th><th>RSSI</th><th>\uc790\uc0b0\ubc88\ud638</th><th>\uc790\uc0b0\uba85</th><th>\ubd80\uc11c</th><th>\uc0c1\ud0dc</th></tr>';\n"
            + "    for(var i=0;i<d.tags.length;i++){\n"
            + "      var t=d.tags[i];\n"
            + "      var rc=t.status==='\ubc18\ucd9c\uc54c\ub9bc'?'tag-alert':(t.status==='\ubc18\ucd9c\ud5c8\uc6a9'?'tag-permitted':'');\n"
            + "      h+='<tr class=\"'+rc+'\">';\n"
            + "      h+='<td>'+esc(t.time)+'</td>';\n"
            + "      h+='<td>'+esc(t.readerName)+'</td>';\n"
            + "      h+='<td>'+esc(t.epc)+'</td>';\n"
            + "      h+='<td>'+t.rssi+'</td>';\n"
            + "      h+='<td>'+esc(t.assetNumber)+'</td>';\n"
            + "      h+='<td>'+esc(t.assetName)+'</td>';\n"
            + "      h+='<td>'+esc(t.department)+'</td>';\n"
            + "      h+='<td>'+esc(t.status)+'</td>';\n"
            + "      h+='</tr>';\n"
            + "    }\n"
            + "    h+='</table>';\n"
            + "    document.getElementById('tags-table').innerHTML=h;\n"
            + "  }).catch(function(e){document.getElementById('tags-table').innerHTML='<div class=\"empty-msg\">\uc624\ub958: '+e.message+'</div>';});\n"
            + "}\n"
            + "\n"
            + "function clearTags(){\n"
            + "  api('DELETE','/api/tags/recent').then(function(r){\n"
            + "    if(r.status==='ok'){showToast('\ud0dc\uadf8 \ucd08\uae30\ud654 \uc644\ub8cc','success');loadTags();}\n"
            + "    else showToast(r.message,'error');\n"
            + "  }).catch(function(e){showToast('\uc624\ub958: '+e.message,'error')});\n"
            + "}\n"
            + "\n"
            + "function startTagPoll(){\n"
            + "  stopTagPoll();\n"
            + "  _tagPollTimer=setInterval(function(){\n"
            + "    api('GET','/api/tags/recent').then(function(r){\n"
            + "      if(r.status==='ok'&&r.data.seq!==_lastTagSeq)loadTags();\n"
            + "    }).catch(function(){});\n"
            + "  },2000);\n"
            + "}\n"
            + "\n"
            + "function stopTagPoll(){if(_tagPollTimer){clearInterval(_tagPollTimer);_tagPollTimer=null;}}\n"
            + "\n"
            + "function esc(s){if(s==null)return '';return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');}\n"
            + "\n"
            + "// Init\n"
            + "var today=new Date();var ymd=today.getFullYear()+'-'+String(today.getMonth()+1).padStart(2,'0')+'-'+String(today.getDate()).padStart(2,'0');\n"
            + "document.getElementById('alert-from').value=ymd+'T00:00';\n"
            + "document.getElementById('alert-to').value=ymd+'T23:59';\n"
            + "loadReaders();\n";
    }
}
